### ISSUE TITLE
技术咨询：在pyminitouch中为同一设备创建多个MNTDevice实例是否安全？

### ISSUE THREAD

**Issue by songyuc** [williamfzc/pyminitouch#24]
尊敬的开发者，您好，

我们正在使用 pyminitouch，并对其与 minitouch 的交互有一些疑问。根据 minitouch 的文档，我们了解到 [minitouch 一次只支持与一个客户端的单一连接](https://github.com/DeviceFarmer/minitouch#:~:text=Note%20that%20currently%20only%20one%20connection%20at%20a%20time%20is%20supported.)。我们想确认，这是否意味着在 pyminitouch 中，我们也不应该在一个 Python 程序中创建多个指向同一设备的 `MNTDevice` 实例？

例如，以下代码是否符合 pyminitouch 的使用准则？
```python
from pyminitouch import MNTDevice

_DEVICE_ID = '123456F'
device1 = MNTDevice(_DEVICE_ID)
device2 = MNTDevice(_DEVICE_ID)

# single-tap
device1.tap([(400, 600)])
# multi-tap
device2.tap([(400, 400), (600, 600)])

device2.stop()
device1.stop()
```
我们希望确保我们的使用方法不会违反 minitouch 的限制，也不会导致任何潜在的问题。非常感谢您的帮助和解答。

**Comment by williamfzc** [comment]
理论上是的，创建多个实例好像没什么意义？
跟随minitouch的限制即可

**Comment by songyuc** [comment]
是这样的，因为我们需要在多个不同函数和类中进行模拟不同模式的点击操作，如果同一设备中只允许创建单个MNTDevice实例的话，我们考虑需要实现**单例模式**来规范“点击器类”的行为；
请问，您在实际使用中有遇到类似的问题吗

**Comment by williamfzc** [comment]
没有的，确实应该用单例

**Comment by songyuc** [comment]
感谢您的解答！
