### ISSUE TITLE
为pyminitouch编写API参考文档

### ISSUE THREAD

**Issue by songyuc** [williamfzc/pyminitouch#28]
@williamfzc 您好，
我是一名对Android测试很感兴趣的学习者，我非常欣赏pyminitouch这个库，认为它是一个非常好的Android测试自动化工具，其中有很多代码值得我们深入学习。

为了让更多新用户可以更容易上手这个优秀的库,我希望可以编写pyminitouch的API参考文档,为这个项目做点贡献。

我预计编写的文档大纲包括:
- 库的概述和特性介绍
- 每个模块和类的API参考
  - 描述、参数、返回值、异常等
- 示例代码演示用法
- 常见用例的使用教程  
- 常见问题解答

我相信完善的API文档可以帮助新用户更快学习和使用pyminitouch进行自己的测试需求。这将有利于项目和社区的长期发展。

如果您认为这个主意不错,也欢迎您对文档的范围和内容提出宝贵意见。我们可以在GitHub或者QQ上进一步讨论细节。

期待您的反馈。如果您赞同,我可以开始编写文档,并以PR的形式提交给您审阅。请指教!

感谢您开发和维护这个非常棒的库!

祝好~

**Comment by williamfzc** [comment]
hello @songyuc 

其实有API文档的：https://pyminitouch.readthedocs.io/en/latest/  

但到目前来说，绝大部分用户基本都能借助 [demo](https://github.com/williamfzc/pyminitouch/blob/master/demo.py) 了解几乎全部pyminitouch暴露的API，**文档反而成为了一个不那么直观的方式**。从我个人感觉出发的话，一个翻译+中文解释过的 demo.py 对新用户可能是个不错的帮助。

BTW，pyminitouch与minitouch都已经进入维护状态了，也偏向底层。如果只是关注测试自动化，有诸如appium与selenium等各种各样更好更活跃的选择，可以选择把宝贵的精力投放在更多人使用的工具上，这样可能对你的帮助更大 ：）

谢谢你的关注

**Comment by songyuc** [comment]
谢谢您的指点！

**Comment by songyuc** [comment]
@williamfzc ，您好，我还想请教一下，对于多指触控来说，pyminitouch是不是比appium支持得更好一些呀？
期待您的回复～

**Comment by williamfzc** [comment]
应该没有好坏一说，两者原理不太一样
appium基于控件树，minitouch是直接跟屏幕交互

minitouch的优势主要是高性能（例如有人拿来做游戏驱动），因为不会处理控件逻辑

**Comment by songyuc** [comment]
喔喔，好的，谢谢您的解答，我们主要也是想做高性能的测试自动化，所以希望继续学习pyminitouch😀
