### ISSUE TITLE
Lower level operation support?

### ISSUE THREAD

**Issue by F6** [williamfzc/pyminitouch#3]
Hi,

Great project. I am working on an AI that plays a mobile phone FPS game, so the outputted actions are really complicated. I see that you have provided high-level apis like tap & swipe, but people may want to use a lower level API like touchpoint.down(),  touchpoint.move(), touchpoint.up(), etc. so that a more complicated action can be generated by other programs.

I see that safe_connection can be used here, but it only wraps a raw socket, so it's not that convenient to use

Cheers

**Comment by williamfzc** [comment]
Thanks for your PR.
Merged: https://github.com/williamfzc/pyminitouch/pull/5
Closed.
